; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "District Dance Battle"
#define MyAppVersion "1.1"
#define MyAppPublisher "FreeStylers Studio"
#define MyAppURL "https://freesstylers.github.io/District-Dance-Battle/"
#define MyAppExeName "DistrictDanceBattle.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E163C7B2-C920-41A6-8F9B-766D29E83B7D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputBaseFilename=DistrictDanceBattle_Installer
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\DistrictDanceBattle.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libFLAC-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libfreetype-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libjpeg-9.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libmodplug-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libmpg123-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libogg-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libpng16-16.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libtiff-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libvorbis-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libvorbisfile-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\libwebp-4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\SDL2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\SDL2_image.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\SDL2_mixer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\SDL2_net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\SDL2_ttf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shoosh\Documents\GitHub\District-Dance-Battle\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

